name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: live
          projectId: sravani-personal-profile
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


      - name: Install Dependencies
        run: npm ci # Use 'ci' for cleaner installs in CI environments

      - name: Build Astro Site
        run: npm run build # Runs the build script defined in package.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # Provided by GitHub Actions
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOUR_PROJECT_ID }}' # Alternative: Service account JSON
          channelId: live # Deploy to the default live channel
          projectId: <your-firebase-project-id> # Replace with your Firebase Project ID
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels # Optional: Enable Hosting previews for PRs later
          # If using FIREBASE_TOKEN instead of Service Account:
          # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}